defaults: &defaults
  working_directory: ~/qmk

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: edasque/qmk_firmware
    steps:
      - checkout
      - run:
          name: "Workaround `x509: failed to load system roots and no roots provided`"
          command: |
            echo "deb http://security.debian.org/debian-security jessie/updates main" >> /etc/apt/sources.list
            apt-get update
            apt-get install -y ca-certificates
      - run:
          name: Build keymap
          command: |
            make clean ; make keyboard=planck/rev4 keymap=lorentzca
            make clean ; make keyboard=planck/rev5 keymap=lorentzca
      - persist_to_workspace:
          root: ~/qmk
          paths:
            - .build/planck_rev4_lorentzca.hex
            - .build/planck_rev5_lorentzca.hex

  publish-github-release:
    <<: *defaults
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ~/qmk
      - run:
          name: Publish Release on GitHub
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete rev4$(date +%Y%m%d%H%M%S) ~/qmk/.build/planck_rev4_lorentzca.hex
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete rev5$(date +%Y%m%d%H%M%S) ~/qmk/.build/planck_rev5_lorentzca.hex

workflows:
  version: 2
  main:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
